package: responsive_preview
version: '1.0.1'
author: 'FriendsOfREDAXO'
supportpage: https://github.com/FriendsOfREDAXO/responsive_preview
compile: 0

page:
  hidden: true
  title: 'Responsive-Preview'
  perm: responsive_preview[]
  pjax: true
  icon: rex-icon fa fa-expand
pages:
  content/preview: { title: 'translate:title', itemClass: 'pull-right', href: "javascript:openPreview()", icon: rex-icon fa fa-mobile }

requires:
    packages:
    redaxo: '>=5.10'
    php:
        version: '>=8.1, <9'
